config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    @user_question = params[:user_question]
    @coach_answer = coach_answer_enhanced(@user_question)
  end

    def coach_answer(your_message)
      if your_message.downcase == "i am going to work right now!"
        ""
      elsif your_message.end_with?("?")
        "Silly question, get dressed and go to work!"
      else
        "I don't care, get dressed and go to work!"
      end
    end

    def coach_answer_enhanced(your_message)
      answer = coach_answer(your_message)
      if answer != ""
        if your_message.upcase == your_message
          "I can feel your motivation! #{answer}"
        else
          answer
        end
      else
        ""
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">

    <div class="cover-container">

      <header class="masthead clearfix">
        <div class="inner">
          <h3 href="ask" class="masthead-brand">Rails Stupid Coach</h3>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h2 class="cover-heading"><%= @coach_answer %></h2>
        <div class=" btn btn-secondary"> <%= link_to "Ask another question?", ask_path %></div>
      </main>

      <footer class="mastfoot">
        <div class="inner">
          <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
      </footer>

    </div>

  </div>

</div>

app/views/questions/ask.html.erb
<div class="site-wrapper">

  <div class="site-wrapper-inner">

    <div class="cover-container">

      <header class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Rails Stupid Coach</h3>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Speak to your coach</h1>
        <form action="/answer">
          <label for="question"></label>
          <input type="text" id="question" name="user_question" placeholder="what time is it?">
          <input class="btn btn-secondary" type="submit" value="Go on!">
        </form>
      </main>

      <footer class="mastfoot">
        <div class="inner">
          <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
      </footer>

    </div>

  </div>

</div>